"""The user-facing inventory of files generated by the test-data notebook."""

BUCKET = "ssb-play-enhjoern-a-data-produkt-test"

PERIODS_AND_VERSIONS = [
    ("2024", 1),
    ("2025", 1),
    ("2026", 1),
    ("2025-Q1", 1),
    ("2025-Q2", 1),
    ("2025-Q3", 1),
    ("2025-Q4", 1),
    ("2026-Q1", 2),
    ("2026-Q2", 2),
    ("2026-Q3", 2),
]

# Add a new valid dataset group here to generate ten files for it.
VALID_DATASET_GROUPS = [
    ("befolkning", "inndata", "befolkning"),
    ("befolkning", "klargjorte-data", "befolkning"),
    ("befolkning", "utdata", "befolkning"),
    ("sysselsetting", "inndata", "sysselsetting"),
    ("sysselsetting", "klargjorte-data", "sysselsetting"),
    ("sysselsetting", "utdata", "sysselsetting"),
    ("utdanning", "klargjorte-data", "utdanning"),
    ("utdanning", "statistikk", "utdanning-nivaa"),
    ("utdanning", "utdata", "utdanning"),
    ("inntekt", "inndata", "personinntekt"),
    ("inntekt", "klargjorte-data", "personinntekt"),
    ("inntekt", "utdata", "personinntekt"),
    ("varehandel", "statistikk", "varehandel-imputert"),
    ("varehandel", "klargjorte-data", "varehandel"),
    ("varehandel", "utdata", "varehandel"),
]

# These paths are accepted by Datadoc but must report naming violations.
NAMING_ERROR_PATHS = [
    *[
        f"{product}/utdata/{name}_{suffix}.parquet"
        for product, name in {
            "befolkning": "befolkning",
            "sysselsetting": "sysselsetting",
            "utdanning": "utdanning",
            "inntekt": "personinntekt",
            "varehandel": "varehandel",
        }.items()
        for suffix in ("p2026-Q1", "p2026-Q1_v1", "2026-Q1_v1", "p2026-Q1_1")
    ],
    *[
        f"{product}/statistikk/{name}_{suffix}.parquet"
        for product, name in {
            "befolkning": "befolkning",
            "sysselsetting": "sysselsetting",
            "utdanning": "utdanning-nivaa",
            "inntekt": "personinntekt",
            "varehandel": "varehandel-imputert",
        }.items()
        for suffix in ("p2025", "p2025_v1")
    ],
]

# These paths cannot be parsed by Datadoc and must return 404.
REJECTED_PATHS = [
    f"{product}/invalid-state/{name}_{suffix}.parquet"
    for product, name in {
        "befolkning": "befolkning",
        "sysselsetting": "sysselsetting",
        "utdanning": "utdanning",
        "inntekt": "personinntekt",
        "varehandel": "varehandel",
    }.items()
    for suffix in ("p2026-Q1", "p2026-Q1_v1", "2026-Q1_v1", "p2026-Q1_1")
]
INVALID_DATASET_PATHS = NAMING_ERROR_PATHS + REJECTED_PATHS

# The deletion cell creates three scenarios: partial, full cascade, and untouched.
PARTIAL_DELETION_PATH = "sysselsetting/klargjorte-data/sysselsetting_p2024_v1.parquet"
CASCADE_DELETION_PRODUCT = "befolkning"
UNTOUCHED_PRODUCT = "sysselsetting"


def valid_paths() -> list[str]:
    return [
        f"{product}/{state}/{description}_p{period}_v{version}.parquet"
        for product, state, description in VALID_DATASET_GROUPS
        for period, version in PERIODS_AND_VERSIONS
    ]


def indexed_valid_paths() -> list[str]:
    return [path for path in valid_paths() if "/klargjorte-data/" in path or "/utdata/" in path]


def deletion_paths() -> list[str]:
    return [
        PARTIAL_DELETION_PATH,
        *[path for path in indexed_valid_paths() if path.startswith(f"{CASCADE_DELETION_PRODUCT}/")],
    ]


def generated_top_level_prefixes() -> set[str]:
    return {path.split("/", 1)[0] for path in valid_paths() + INVALID_DATASET_PATHS}
